import "server-only";
import { promises as fs } from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import type { Application } from "./types";

/**
 * File-system application store.
 *   STORAGE_DIR/applications.json  – all application records
 *   STORAGE_DIR/resumes/<id>.<ext> – uploaded resume files
 *
 * Writes are serialised through a promise chain and committed with an
 * atomic rename so a crash never leaves a half-written JSON file.
 * Swap this module for a DB/S3 implementation with the same exports.
 */

const ROOT = path.resolve(
  /* turbopackIgnore: true */ process.cwd(),
  process.env.STORAGE_DIR?.trim() || "storage",
);
const DB_FILE = path.join(ROOT, "applications.json");
const RESUME_DIR = path.join(ROOT, "resumes");

let writeChain: Promise<unknown> = Promise.resolve();

async function ensureDirs() {
  await fs.mkdir(RESUME_DIR, { recursive: true });
}

async function readAll(): Promise<Application[]> {
  try {
    return JSON.parse(await fs.readFile(DB_FILE, "utf8")) as Application[];
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code === "ENOENT") return [];
    throw e;
  }
}

async function writeAll(apps: Application[]) {
  const tmp = `${DB_FILE}.${process.pid}.${Date.now()}.tmp`;
  await fs.writeFile(tmp, JSON.stringify(apps, null, 2), "utf8");
  await fs.rename(tmp, DB_FILE);
}

function withLock<T>(fn: () => Promise<T>): Promise<T> {
  const run = writeChain.then(fn, fn);
  writeChain = run.catch(() => undefined);
  return run;
}

export class DuplicateApplicationError extends Error {}

export function newApplicationId() {
  return `app_${Date.now().toString(36)}_${crypto.randomBytes(5).toString("hex")}`;
}

export async function saveApplication(
  app: Omit<Application, "resume"> & { resume: Omit<Application["resume"], "storedName"> },
  file: { buf: Buffer; ext: string },
): Promise<Application> {
  return withLock(async () => {
    await ensureDirs();
    const all = await readAll();
    const email = app.candidate.email.toLowerCase();
    if (all.some((a) => a.jobId === app.jobId && a.candidate.email.toLowerCase() === email)) {
      throw new DuplicateApplicationError("You have already applied to this job with this email.");
    }
    const storedName = `${app.id}.${file.ext}`;
    await fs.writeFile(path.join(RESUME_DIR, storedName), file.buf);
    const record: Application = { ...app, resume: { ...app.resume, storedName } };
    all.push(record);
    try {
      await writeAll(all);
    } catch (e) {
      await fs.rm(path.join(RESUME_DIR, storedName), { force: true });
      throw e;
    }
    return record;
  });
}

export async function listApplications(jobId?: string): Promise<Application[]> {
  const all = await readAll();
  return (jobId ? all.filter((a) => a.jobId === jobId) : all).sort(
    (a, b) => Date.parse(b.createdAt) - Date.parse(a.createdAt),
  );
}

export async function getApplication(id: string): Promise<Application | undefined> {
  return (await readAll()).find((a) => a.id === id);
}

export async function updateApplicationStatus(id: string, status: Application["status"]) {
  return withLock(async () => {
    const all = await readAll();
    const app = all.find((a) => a.id === id);
    if (!app) return undefined;
    app.status = status;
    await writeAll(all);
    return app;
  });
}

export async function readResumeFile(app: Application): Promise<Buffer> {
  // storedName is generated by us, but guard against path traversal anyway
  const safe = path.basename(app.resume.storedName);
  return fs.readFile(path.join(RESUME_DIR, safe));
}
